### ISSUE TITLE
Import packages in DESCRIPTION

### ISSUE THREAD

**Issue by boyiguo1** [MicTott/SpotSweeper#2]
There are functions imported from extenernal packages, such as `MASS` and `dbscan`. While the functions are correctly imported to the namesspace, it is also mandatory to imports these packages in the DESCRIPTION file to set up correct dependency during installation. Otherwise, it will lead to errors during `devtools::check(document = FALSE)`. See the message below.
```
E  checking package dependencies (2s)
   Namespace dependencies missing from DESCRIPTION Imports/Depends entries:
     'BiocParallel', 'MASS', 'dbscan', 'spatialLIBD'
```

To fix it, you can simply adding these packages to the the `Imports` field in the DESCRIPTION file. See more detail via https://r-pkgs.org/description.html#sec-description-imports-suggests. I think for now, you can simply `Imports` instead of `Depends`.

**Comment by MicTott** [comment]
Done
