### ISSUE TITLE
[Suggestion] Remove `example_SPE.R

### ISSUE THREAD

**Issue by boyiguo1** [MicTott/SpotSweeper#3]
If you need an example Visium data with only one sample, you can simply use [`STexampleData`](https://bioconductor.org/packages/release/data/experiment/html/STexampleData.html) via `spe <- Visium_humanDLPFC()`.

You can put `STexampleData` as `Suggests` in your DESCRIPTION file.

The reasons are 
* Loading all DLPFC samples using `spatialLIBD` could take a lot of memory space and time
* You package will depend on `spatialLIBD` which will depends on all packages that `spatialLIBD` depends on which is a lot, and you won't need them.

**Comment by MicTott** [comment]
Done
